# Flutter の推奨リントセットを使用
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports       # 相対パスでのimportを禁止
    - directives_ordering              # インポートの順序を整理
    - prefer_final_locals              # 再代入されない変数はfinalにする
    - prefer_const_declarations        # const で宣言できるものは const にする
    - prefer_const_constructors        # const で作れるウィジェットに const を強制
    - sort_constructors_first          # コンストラクタを最初に定義
    - prefer_single_quotes             # シングルクォートを推奨
    - sort_pub_dependencies            # pubspec.yaml の dependencies の順序を整理
    - avoid_print                      # print() の使用を避ける

analyzer:
  errors:
    unused_import: error                # 未使用の import はエラーとして扱う
    invalid_annotation_target: ignore   # アノテーションの警告を無視
    constant_identifier_names: ignore
